### ISSUE TITLE
Tags?

### ISSUE THREAD

**Issue by iyanmv** [WardBrian/stanio#3]
Hi @WardBrian 

Could you provide tags (or releases) matching the releases at PyPI?

It would be useful to package this for distros that prefer GitHub over PyPI to get the source code (e.g. [Arch Linux](https://rfc.archlinux.page/0020-sources-for-python-packaging/)).

**Comment by WardBrian** [comment]
I've added tags for the two most recent releases and have made a note to do so in the future.

**Comment by iyanmv** [comment]
Great, thanks!
